# Site Settings
title: My profile
url: 'http://webjeda.com'
baseurl: '/profile-vc' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Ivan Rojas
tagline: Full Stack Developer
pic: perfil.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Estudiante de Ingeniería de Sistemas y Computación con capacidad de trabajo en grupo, comunicación asertiva, seguimiento de instrucciones, iniciativa y aprendizaje; con interés en desempeñarse en el área de desarrollo, con manejo de programación estructurada, programación orientada a objetos y estructuras de datos; Lenguaje de Marcado de Hipertexto (HTML5); lenguaje de hojas de estilo CSS; lenguajes de programación como C, C++, Java, Python, Angular 2, Ruby, R, Pascal y JavaScript; herramientas de construcción de lenguajes de programación como Flex, Bison y ANTLR4; modelado y manejo básico de bases de datos (MySQL).  Mas de tres años de experiencia en ventas y atención al público en comercio al por menor de víveres, con gran iniciativa y habilidades para interactuar en el área de ventas. '

#sidebar links
email: idrojasf@unal.edu.co
phone: 3134505568
github: idrojasf
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
